const key='trip-together-v1';
const defaultState={trip:{title:'石垣島旅行',dates:'8/17〜8/19'},members:[{id:'a',name:'しゅうた',color:'#e75d38'},{id:'b',name:'Aさん',color:'#2a9d8f'},{id:'c',name:'Bさん',color:'#4c78c2'}],current:'a',proposals:[],events:[],expenses:[]};
let state=JSON.parse(localStorage.getItem(key)||'null')||defaultState;
state.logs=state.logs||[];let editingProposalId=null,editingEventId=null;
const $=s=>document.querySelector(s); const byId=id=>document.getElementById(id);
function save(){localStorage.setItem(key,JSON.stringify(state));render()}
function member(id){return state.members.find(x=>x.id===id)}
function log(action,detail){state.logs.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),person:state.current,action,detail});state.logs=state.logs.slice(0,100)}
function safeMapUrl(value){try{const url=new URL(value);return url.protocol==='https:'?url.href:''}catch{return ''}}
function mapPlaceName(value){try{const url=new URL(value),path=decodeURIComponent(url.pathname);let found=path.match(/\/place\/([^/]+)/);if(found)return found[1].replace(/\+/g,' ');let query=url.searchParams.get('query')||url.searchParams.get('q');return query?query.replace(/\+/g,' '):''}catch{return ''}}
function yen(n){return new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n)}
function netBalances(){const net=Object.fromEntries(state.members.map(m=>[m.id,0]));(state.expenses||[]).forEach(e=>{net[e.payer]+=e.amount;Object.entries(e.shares).forEach(([id,n])=>net[id]-=n)});return net}
function settlement(net){let debt=Object.entries(net).filter(([,n])=>n<-.5).map(([id,n])=>({id,n:-n})),credit=Object.entries(net).filter(([,n])=>n>.5).map(([id,n])=>({id,n})),out=[];while(debt.length&&credit.length){let a=debt[0],b=credit[0],n=Math.min(a.n,b.n);out.push({from:a.id,to:b.id,n:Math.round(n)});a.n-=n;b.n-=n;if(a.n<.5)debt.shift();if(b.n<.5)credit.shift()}return out}
function payerOptions(){return `<option value="__self__">各自で支払い</option>${state.members.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}`}
function typeName(type){return ({activity:'予定',transport:'交通',stay:'宿泊',meal:'食事',attraction:'観光施設',other:'その他'})[type]||'予定'}
function addCostEntries(title,payer,shares,method,scheduleId){state.expenses=state.expenses||[];if(payer==='__self__'){Object.entries(shares).forEach(([id,amount])=>state.expenses.push({id:crypto.randomUUID(),scheduleId,title,amount,payer:id,method:'各自で支払い',shares:{[id]:amount}}))}else{const amount=Object.values(shares).reduce((a,b)=>a+b,0);state.expenses.push({id:crypto.randomUUID(),scheduleId,title,amount,payer,method,shares})}}
function render(){
  $('#tripTitle').textContent=state.trip.title; $('#tripDates').textContent=state.trip.dates;
  const cur=member(state.current);$('#identityButton').textContent='👤 操作中：'+(cur?.name||'未選択');$('#proposalCount').textContent=state.proposals.length;
  $('#members').innerHTML=state.members.map(m=>`<span class="member"><i class="dot" style="background:${m.color}"></i>${m.name}</span>`).join('')||'<p class="empty">参加者を追加してください。</p>';
  $('#activityLogs').innerHTML=state.logs.length?state.logs.map(l=>`<div class="logItem"><b>${member(l.person)?.name||'不明'}</b> が ${l.action}<small>${l.detail||''} · ${new Date(l.at).toLocaleString('ja-JP')}</small></div>`).join(''):'<p class="empty">まだ操作ログはありません。</p>';
  const day=$('#datePicker').value;const stays=state.events.filter(e=>e.type==='stay'&&(!day||e.date===day||e.endDate===day));const events=state.events.filter(e=>e.type!=='stay'&&(!day||e.date===day)).sort((a,b)=>(a.start||'99').localeCompare(b.start||'99'));
  $('#stayTimeline').innerHTML=stays.length?stays.map(e=>`<article class="stayLane"><span class="stayLabel">宿泊</span><h3>${e.title}</h3><p>${e.mapPlace||mapPlaceName(e.mapUrl)||''}</p><p>チェックイン ${e.checkIn||'未定'}${e.checkInFrom?'（開始：'+e.checkInFrom+'〜）':''}　チェックアウト ${e.checkOut||'未定'}${e.checkOutUntil?'（締切：'+e.checkOutUntil+'）':''}</p>${e.ota?`<p>予約先：${e.ota}</p>`:''}${e.costLabel?`<p>費用：${e.costLabel}</p>`:''}${e.cancelPolicy?`<p>キャンセル：${e.cancelPolicy}</p>`:''}${safeMapUrl(e.mapUrl)?`<a class="mapLink" href="${safeMapUrl(e.mapUrl)}" target="_blank" rel="noopener noreferrer">Google Mapsで開く ↗</a>`:''}<button class="editButton" data-edit-event="${e.id}">編集</button></article>`).join(''):'';
  $('#timeline').innerHTML=events.length?events.map(e=>`<article class="event"><time>${e.start||'時間未定'}${e.end?'–'+e.end:''}</time><div class="eventBody type-${e.type||'activity'}" style="border-color:${member(e.participants[0])?.color||'#e75d38'}"><strong><span class="typeBadge type-${e.type||'activity'}">${typeName(e.type||'activity')}</span>${e.title}</strong><small>${e.type==='transport'?(e.transportMode||'交通')+(e.reserved?' · 予約済み':' · 未予約')+(e.costLabel?' · '+e.costLabel:''):(e.mapPlace||mapPlaceName(e.mapUrl)||'')}</small>${safeMapUrl(e.mapUrl)?`<a class="mapLink" href="${safeMapUrl(e.mapUrl)}" target="_blank" rel="noopener noreferrer">Google Mapsで開く ↗</a>`:''}${e.participants.map(id=>`<span class="chip">${member(id)?.name}</span>`).join('')}<button class="editButton" data-edit-event="${e.id}">編集</button></div></article>`).join(''):'<p class="empty">この日の確定予定はまだありません。</p>';
  $('#proposals').innerHTML=state.proposals.length?state.proposals.map(p=>{const mine=p.votes[state.current];return `<article class="proposal"><h3>${p.title}</h3><p class="meta">${p.date}${p.start?' '+p.start:''}${p.mapPlace||mapPlaceName(p.mapUrl)||''}　提案：${member(p.author)?.name||''}</p>${p.cost?`<p class="meta">費用：${member(p.costPayer)?.name||'各自で支払い'} が ${yen(p.cost)}</p>`:''}<div class="votes">${p.participants.map(id=>`<button class="vote ${p.votes[id]==='参加したい'?'active':''}" data-vote="${p.id}" data-person="${id}">${member(id)?.name}：${p.votes[id]||'未回答'}</button>`).join('')}</div><button class="adopt" data-adopt="${p.id}">この参加者で予定に追加</button><button class="editButton" data-edit-proposal="${p.id}">編集</button></article>`}).join(''):'<p class="empty">未処理の提案はありません。気になることを気軽に追加しましょう。</p>';
  const net=netBalances();$('#expenseSummary').innerHTML=state.members.map(m=>`<div class="balance">${m.name}<strong class="${net[m.id]>=0?'positive':'negative'}">${net[m.id]>=0?'+':''}${yen(net[m.id])}</strong></div>`).join('');
  $('#expenses').innerHTML=(state.expenses||[]).length?state.expenses.slice().reverse().map(e=>`<article class="proposal"><div class="expenseLine"><h3>${e.title}</h3><b>${yen(e.amount)}</b></div><p class="meta">支払い：${member(e.payer)?.name}　${e.method==='equal'?'均等割り':e.method==='amount'?'金額指定':'割合指定'}</p><p class="meta">${Object.entries(e.shares).map(([id,n])=>`${member(id)?.name} ${yen(n)}`).join(' · ')}</p></article>`).join(''):'<p class="empty">費用はまだ登録されていません。</p>';
  const moves=settlement(net);$('#settlements').innerHTML=`<h3>精算の提案</h3>${moves.length?moves.map(x=>`<p><b>${member(x.from)?.name}</b> → <b>${member(x.to)?.name}</b>　${yen(x.n)}</p>`).join(''):'<p>精算は完了しています。</p>'}`;
}
function choices(container,checked=true){container.innerHTML=state.members.map(m=>`<label class="choice"><input type="checkbox" name="participants" value="${m.id}" ${checked?'checked':''}>${m.name}</label>`).join('')}
$('#openMember').onclick=()=>byId('memberDialog').showModal();
$('#memberForm').addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target),name=d.get('name');state.members.push({id:crypto.randomUUID(),name,color:d.get('color')});log('参加者を追加',''+name);e.target.reset();byId('memberDialog').close();save()});
function openProposal(){editingProposalId=null;choices($('#participantChoices'));$('#proposalCostPayer').innerHTML=payerOptions();$('#proposalCostPayer').value=state.current;$('#proposalForm').reset();$('#proposalForm [name=date]').value=$('#datePicker').value||new Date().toISOString().slice(0,10);byId('proposalDialog').showModal()}
$('#openProposal').onclick=openProposal;$('#openProposalSmall').onclick=openProposal;
$('#proposalForm').addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target),participants=d.getAll('participants'),mapUrl=d.get('mapUrl'),cost=Number(d.get('proposalCost'));if(mapUrl&&!safeMapUrl(mapUrl))return alert('httpsから始まるGoogle Mapsのリンクを入力してください。');if(cost&&!participants.length)return alert('費用を分ける参加候補を選んでください。');let old=editingProposalId&&state.proposals.find(x=>x.id===editingProposalId),votes=old?.votes||{};let p={id:old?.id||crypto.randomUUID(),type:d.get('type'),title:d.get('title'),date:d.get('date'),start:d.get('start'),end:d.get('end'),mapUrl,mapPlace:mapPlaceName(mapUrl),participants,author:old?.author||state.current,cost,costPayer:d.get('proposalCostPayer'),votes};participants.forEach(id=>p.votes[id]=p.votes[id]||'未回答');if(old){Object.assign(old,p);log('提案を編集',p.title)}else{participants.forEach(id=>p.votes[id]=id===state.current?'参加したい':p.votes[id]);state.proposals.unshift(p);log('提案を追加',p.title)}editingProposalId=null;e.target.reset();byId('proposalDialog').close();save()});
$('#identityButton').onclick=()=>{let box=$('#identityChoices');box.innerHTML='';state.members.forEach(m=>{let b=document.createElement('button');b.className='identityChoice';b.value='cancel';b.textContent=m.name;b.onclick=()=>{state.current=m.id;byId('identityDialog').close();save()};box.append(b)});byId('identityDialog').showModal()};
function scheduleCostFields(){const type=$('#scheduleType').value,people=[...document.querySelectorAll('[name=schedulePeople]:checked')].map(x=>x.value);$('#scheduleCostFields').hidden=!['stay','transport'].includes(type);$('#stayCostFields').hidden=type!=='stay';$('#transportCostFields').hidden=type!=='transport';$('#stayCostLabel').firstChild.textContent=$('#stayChargeType').value==='room'?'ルームチャージ（円）':'一人あたりの宿泊料金（円）';$('#transportCostInputs').innerHTML=people.map(id=>`<label>${member(id)?.name}の交通費（円）<input class="transportCost" data-id="${id}" min="0" type="number" inputmode="numeric" placeholder="例：12800"></label>`).join('')}
function scheduleFields(){const type=$('#scheduleType').value,isStay=type==='stay',start=$('#regularTimes [name=start]'),end=$('#regularTimes [name=end]');$('#stayTimes').hidden=!isStay;$('#regularTimes').hidden=isStay;start.disabled=isStay;end.disabled=isStay;if(isStay){start.value='';end.value=''}$('#stayBookingFields').hidden=!isStay;$('#transportFields').hidden=type!=='transport';scheduleCostFields()}
$('#scheduleType').onchange=scheduleFields;
$('#openSchedule').onclick=()=>{const picks=$('#scheduleParticipants'),payer=$('#costPayerChoices');picks.innerHTML=state.members.map(m=>`<label class="choice"><input type="checkbox" name="schedulePeople" value="${m.id}" checked>${m.name}</label>`).join('');payer.innerHTML=payerOptions();payer.value=state.current;$('#scheduleForm [name=date]').value=$('#datePicker').value||new Date().toISOString().slice(0,10);scheduleFields();byId('scheduleDialog').showModal()};
$('#scheduleParticipants').onchange=scheduleCostFields;$('#stayChargeType').onchange=scheduleCostFields;
$('#scheduleForm').addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target),mapUrl=d.get('mapUrl'),type=d.get('type'),people=d.getAll('schedulePeople'),eventId=crypto.randomUUID(),shares={},cost=0,costLabel='';if(mapUrl&&!safeMapUrl(mapUrl))return alert('httpsから始まるGoogle Mapsのリンクを入力してください。');if(['stay','transport'].includes(type)&&!people.length)return alert('費用を分ける参加者を1人以上選んでください。');if(type==='stay'&&Number(d.get('stayCost'))>0){const unit=Number(d.get('stayCost'));if(d.get('stayChargeType')==='room'){cost=unit;let base=Math.floor(cost/people.length),rest=cost-base*people.length;people.forEach((id,i)=>shares[id]=base+(i<rest?1:0));costLabel='ルームチャージ '+yen(cost)}else{cost=unit*people.length;people.forEach(id=>shares[id]=unit);costLabel='一人あたり '+yen(unit)}}if(type==='transport'){[...document.querySelectorAll('.transportCost')].forEach(x=>{let n=Number(x.value);if(n>0){shares[x.dataset.id]=n;cost+=n}});if(cost)costLabel='合計 '+yen(cost)}const entry={id:eventId,type,title:d.get('title'),date:d.get('date'),endDate:d.get('endDate'),start:d.get('start'),end:d.get('end'),checkIn:d.get('checkIn'),checkInFrom:d.get('checkInFrom'),checkOut:d.get('checkOut'),checkOutUntil:d.get('checkOutUntil'),transportMode:d.get('transportMode'),reserved:d.get('reserved')==='on',mapUrl,mapPlace:mapPlaceName(mapUrl),ota:d.get('ota'),cancelPolicy:d.get('cancelPolicy'),participants:people,author:state.current,costLabel};state.events.push(entry);if(cost)addCostEntries(d.get('title'),d.get('costPayer'),shares,type==='stay'?d.get('stayChargeType'):'金額指定',eventId);e.target.reset();byId('scheduleDialog').close();save()});
function splitFields(){const method=$('#splitMethod').value,people=[...document.querySelectorAll('[name=expensePeople]:checked')].map(x=>x.value);$('#splitInputs').innerHTML=method==='equal'?'':people.map(id=>`<label>${member(id)?.name}${method==='amount'?'の負担額（円）':'の割合（%）'}<input required class="splitValue" data-id="${id}" min="0" type="number" inputmode="decimal" value="${method==='ratio'?(100/Math.max(people.length,1)).toFixed(2):''}"></label>`).join('');$('#splitNotice').textContent=''}
$('#openExpense').onclick=()=>{let people=$('#expenseParticipants'),payer=$('#payerChoices');payer.innerHTML=state.members.map(m=>`<option value="${m.id}">${m.name}</option>`).join('');payer.value=state.current;people.innerHTML=state.members.map(m=>`<label class="choice"><input type="checkbox" name="expensePeople" value="${m.id}" checked>${m.name}</label>`).join('');splitFields();byId('expenseDialog').showModal()};$('#splitMethod').onchange=splitFields;$('#expenseParticipants').onchange=splitFields;
$('#expenseForm').addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target),amount=Number(d.get('amount')),method=d.get('method'),people=d.getAll('expensePeople'),shares={};if(!people.length)return $('#splitNotice').textContent='負担する人を選んでください。';if(method==='equal'){let base=Math.floor(amount/people.length),rest=amount-base*people.length;people.forEach((id,i)=>shares[id]=base+(i<rest?1:0))}else{let vals=[...document.querySelectorAll('.splitValue')];if(method==='amount'){vals.forEach(x=>shares[x.dataset.id]=Number(x.value));if(Object.values(shares).reduce((a,b)=>a+b,0)!==amount)return $('#splitNotice').textContent='負担額の合計を費用総額と一致させてください。'}else{let total=vals.reduce((a,x)=>a+Number(x.value),0);if(Math.abs(total-100)>.01)return $('#splitNotice').textContent='割合の合計を100%にしてください。';let used=0;vals.forEach((x,i)=>{shares[x.dataset.id]=i===vals.length-1?amount-used:Math.round(amount*Number(x.value)/100);used+=shares[x.dataset.id]})}}state.expenses=state.expenses||[];state.expenses.push({id:crypto.randomUUID(),title:d.get('title'),amount,payer:d.get('payer'),method,shares});e.target.reset();byId('expenseDialog').close();save()});
$('#proposals').onclick=e=>{let vote=e.target.dataset.vote,adopt=e.target.dataset.adopt,edit=e.target.dataset.editProposal;if(edit){let p=state.proposals.find(x=>x.id===edit);editingProposalId=p.id;choices($('#participantChoices'),false);$('#proposalCostPayer').innerHTML=payerOptions();$('#proposalForm [name=title]').value=p.title;$('#proposalForm [name=date]').value=p.date;$('#proposalForm [name=start]').value=p.start||'';$('#proposalForm [name=end]').value=p.end||'';$('#proposalForm [name=mapUrl]').value=p.mapUrl||'';$('#proposalForm [name=proposalCost]').value=p.cost||'';$('#proposalCostPayer').value=p.costPayer||state.current;document.querySelectorAll('[name=participants]').forEach(x=>x.checked=p.participants.includes(x.value));byId('proposalDialog').showModal();return}if(vote){let p=state.proposals.find(x=>x.id===vote);let id=e.target.dataset.person;if(id===state.current){p.votes[id]=p.votes[id]==='参加したい'?'行かない':'参加したい';log('提案への参加意思を変更',p.title);save()}}if(adopt){let i=state.proposals.findIndex(x=>x.id===adopt),p=state.proposals[i];let attendees=p.participants.filter(id=>p.votes[id]==='参加したい');let eventId=crypto.randomUUID();state.events.push({...p,id:eventId,participants:attendees.length?attendees:p.participants});if(p.cost){let people=attendees.length?attendees:p.participants,base=Math.floor(p.cost/people.length),rest=p.cost-base*people.length,shares={};people.forEach((id,n)=>shares[id]=base+(n<rest?1:0));addCostEntries(p.title,p.costPayer,shares,'均等割り',eventId)}state.proposals.splice(i,1);log('提案を予定に追加',p.title);save()}};
$('#exportJson').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='trip-together-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#importJson').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{state=JSON.parse(r.result);state.logs=state.logs||[];save()}catch{alert('読み込めないファイルです。')}};r.readAsText(f)};
document.addEventListener('click',e=>{const id=e.target.dataset.editEvent;if(!id)return;const item=state.events.find(x=>x.id===id);if(!item)return;const title=prompt('予定名を編集',item.title);if(title===null)return;const date=prompt('日付を編集（YYYY-MM-DD）',item.date)||item.date;const start=item.type==='stay'?'':prompt('開始時刻を編集（HH:MM、不要なら空欄）',item.start||'');item.title=title;item.date=date;if(item.type!=='stay')item.start=start;log('予定を編集',item.title);save()});
$('#datePicker').onchange=render; render();

