Warning: truncated output (original token count: 13446)
Total output lines: 104

const key='trip-together-v1';
const remoteConfig=window.TRIP_SUPABASE_CONFIG;
const db=window.supabase&&remoteConfig?window.supabase.createClient(remoteConfig.url,remoteConfig.publishableKey):null;
let remoteUser=null,remoteTimer;
let realtimeChannel=null,applyingRemote=false;
const defaultState={trip:{title:'',dates:'',onboarded:false},members:[],current:null,proposals:[],events:[],expenses:[]};
let state=JSON.parse(localStorage.getItem(key)||'null')||defaultState;
if(state.trip.title&&!('onboarded' in state.trip))state.trip.onboarded=true;
state.logs=state.logs||[];let editingProposalId=null,editingEventId=null,timelineView='time';
const $=s=>document.querySelector(s); const byId=id=>document.getElementById(id);
function save(){localStorage.setItem(key,JSON.stringify(state));render();if(db&&state.trip.remoteId&&!applyingRemote){clearTimeout(remoteTimer);remoteTimer=setTimeout(syncRemote,500)}}
async function ensureRemoteUser(){if(!db)return null;let {data:{user}}=await db.auth.getUser();if(!user){const {data,error}=await db.auth.signInAnonymously();if(error)throw error;user=data.user}remoteUser=user;return user}
async function syncRemote(){if(!db||!state.trip.remoteId)return;const {error}=await db.from('trips').update({title:state.trip.title,research_consent:!!state.trip.researchConsent,state,updated_at:new Date().toISOString()}).eq('id',state.trip.remoteId);if(error)console.warn('共有保存に失敗しました',error.message)}
async function createInviteLink(){const {data,error}=await db.rpc('create_trip_invite',{p_trip_id:state.trip.remoteId});if(error)throw error;return `${location.origin}${location.pathname}?invite=${data}`}
async function createRemoteTrip(){if(!db)return;await ensureRemoteUser();const {data,error}=await db.rpc('create_shared_trip',{p_title:state.trip.title,p_research_consent:!!state.trip.researchConsent,p_state:state,p_display_name:member(state.current).name});if(error)throw error;state.trip.remoteId=data;await syncRemote();try{const link=await createInviteLink();try{await navigator.clipboard.writeText(link)}catch{}}catch(error){console.warn('招待リンクの自動発行に失敗しました',error.message)}location.assign(`${location.pathname}?trip=${data}`)}
async function joinRemoteTrip(inviteUrl,participantId,name){const token=new URL(inviteUrl).searchParams.get('invite'),isNew=participantId==='__new__',resolvedId=isNew?crypto.randomUUID():participantId;await ensureRemoteUser();const {data:tripId,error}=await db.rpc('join_trip_by_invite',{p_token:token,p_participant_id:resolvedId,p_new_name:name});if(error)throw error;const {data,error:readError}=await db.from('trips').select('*').eq('id',tripId).single();if(readError)throw readError;state=data.state;state.trip=state.trip||{};state.trip.remoteId=tripId;if(isNew)state.members.push({id:resolvedId,name,color:'#4c78c2'});state.current=resolvedId;history.replaceState(null,'',`${location.pathname}?trip=${tripId}`);startRealtime();save()}
function startRealtime(){if(!db||!state.trip.remoteId)return;if(realtimeChannel)db.removeChannel(realtimeChannel);realtimeChannel=db.channel(`trip:${state.trip.remoteId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'trips',filter:`id=eq.${state.trip.remoteId}`},payload=>{const incoming=payload.new.state;if(!incoming||JSON.stringify(incoming)===JSON.stringify(state))return;applyingRemote=true;state=incoming;state.trip=state.trip||{};state.trip.remoteId=payload.new.id;state.trip.title=payload.new.title;state.trip.researchConsent=payload.new.research_consent;state.logs=state.logs||[];localStorage.setItem(key,JSON.stringify(state));render();applyingRemote=false}).subscribe()}
async function showDirectJoin(){const input=$('#joinTripForm [name=inviteUrl]'),token=new URLSearchParams(location.search).get('invite');input.value=location.href;const {data,error}=await db.rpc('get_trip_join_options',{p_token:token});if(error)throw error;const box=$('#joinParticipantButtons');box.innerHTML=(data||[]).map(x=>`<button type="button" data-participant="${x.participant_id}">${x.participant_name}として参加</button>`).join('');box.onclick=async e=>{const id=e.target.dataset.participant;if(!id)return;try{await joinRemoteTrip(input.value,id,'');byId('joinInfoDialog').close()}catch(error){alert('参加できませんでした：'+error.message)}};byId('joinInfoDialog').showModal()}
async function loadRemoteTrip(){if(!db)return;const params=new URLSearchParams(location.search),token=params.get('invite'),tripId=params.get('trip');if(token){await ensureRemoteUser();return showDirectJoin()}if(!tripId)return;try{await ensureRemoteUser();const {data,error}=await db.from('trips').select('*').eq('id',tripId).single();if(error){showDirectJoin();return}state=data.state;state.trip=state.trip||{};state.trip.remoteId=tripId;state.trip.title=data.title;state.trip.researchConsent=data.research_consent;state.logs=state.logs||[];localStorage.setItem(key,JSON.stringify(state));startRealtime();render()}catch(e){console.warn(e);showDirectJoin()}}
function member(id){return state.members.find(x=>x.id===id)}
function log(action,detail){state.logs.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),person:state.current,action,detail});state.logs=state.logs.slice(0,100)}
function safeMapUrl(value){try{const url=new URL(value);return url.protocol==='https:'?url.href:''}catch{return ''}}
function addDays(date,n){if(!date)return '';let d=new Date(date+'T00:00:00');d.setDate(d.getDate()+Number(n));return d.toISOString().slice(0,10)}
function occursOn(event,date){return !date||!event.date||date>=event.date&&date<=(event.endDate||event.date)}
function stayNights(form){const date=form.querySelector('[name=date]'),end=form.querySelector('[name=endDate]');if(!date||!end)return;end.parentElement.hidden=true;let picker=form.querySelector('.stayNights');if(!picker){picker=document.createElement('label');picker.className='stayNights';picker.innerHTML='宿泊日数<select><option value="1">1泊</option><option value="2">2泊</option><option value="3">3泊</option><option value="4">4泊</option><option value="5">5泊</option><option value="6">6泊</option><option value="7">7泊</option></select>';end.parentElement.after(picker);picker.querySelector('select').onchange=()=>end.value=addDays(date.value,picker.querySelector('select').value);date.onchange=()=>end.value=addDays(date.value,picker.querySelector('select').value)}picker.hidden=false;picker.style.display='';end.value=addDays(date.value,picker.querySelector('select').value)}
function mapPlaceName(value){try{const url=new URL(value),path=decodeURIComponent(url.pathname);let found=path.match(/\/place\/([^/]+)/);if(found)return found[1].replace(/\+/g,' ');let query=url.searchParams.get('query')||url.searchParams.get('q');return query?query.replace(/\+/g,' '):''}catch{return ''}}
function yen(n){return new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n)}
function netBalances(){const net=Object.fromEntries(state.members.map(m=>[m.id,0]));(state.expenses||[]).forEach(e=>{net[e.payer]+=e.amount;Object.entries(e.shares).forEach(([id,n])=>net[id]-=n)});return net}
function settlement(net){let debt=Object.entries(net).filter(([,n])=>n<-.5).map(([id,n])=>({id,n:-n})),credit=Object.entries(net).filter(([,n])=>n>.5).map(([id,n])=>({id,n})),out=[];while(debt.length&&credit.length){let a=debt[0],b=credit[0],n=Math.min(a.n,b.n);out.push({from:a.id,to:b.id,n:Math.round(n)});a.n-=n;b.n-=n;if(a.n<.5)debt.shift();if(b.n<.5)credit.shift()}return out}
function payerOptions(){return `<option value="__self__">各自で支払い</option>${state.members.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}`}
function typeName(type){return ({activity:'予定',transport:'交通',stay:'宿泊',meal:'食事',attraction:'観光施設',other:'その他'})[type]||'予定'}
function typeColor(type){return ({activity:'#e75d38',transport:'#4476b9',stay:'#278468',meal:'#c46725',attraction:'#7a5bbb',other:'#687582'})[type]||'#e75d38'}
function addCostEntries(title,payer,shares,method,scheduleId){state.expenses=state.expenses||[];if(payer==='__self__'){Object.entries(shares).forEach(([id,amount])=>state.expenses.push({id:crypto.randomUUID(),scheduleId,title,amount,payer:id,method:'各自で支払い',shares:{[id]:amount}}))}else{const amount=Object.values(shares).reduce((a,b)=>a+b,0);state.expenses.push({id:crypto.randomUUID(),scheduleId,title,amount,payer,method,shares})}log('費用を追加',title)}
function render(){
  const forceHome=new URLSearchParams(location.search).get('home')==='1',started=!!state.trip.onboarded&&!forceHome;if($('#siteHeader'))$('#siteHeader').hidden=!started;if($('#tripToolbar'))$('#tripToolbar').hidden=!started;if($('#welcomeScreen'))$('#welcomeScreen').hidden=started;if($('#appMain'))$('#appMain').hidden=!started;
  $('#tripTitle').textContent=state.trip.title; $('#tripDates').textContent=state.trip.dates||'';$('#tripDates').hidden=!state.trip.dates||state.trip.dates==='日程未設定';
  const cur=member(state.current);$('#identityButton').textContent='編集中の参加者：'+(cur?.name||'未選択');if($('#identityButtonBottom'))$('#identityButtonBottom').textContent='編集中の参加者：'+(cur?.name||'未選択');if($('#proposalCount'))$('#proposalCount').textContent=state.proposals.length;
  $('#members').innerHTML=state.members.map(m=>`<span class="member"><i class="dot" style="background:${m.color}"></i>${m.name}</span>`).join('')||'<p class="empty">参加者を追加してください。</p>';
  $('#activityLogs').innerHTML=state.logs.length?state.logs.map(l=>`<div class="logItem"><b>${member(l.person)?.name||'不明'}</b> が ${l.action}<small>${l.detail||''} · ${new Date(l.at).toLocaleString('ja-JP')}</small></div>`).join(''):'<p class="empty">まだ操作ログはありません。</p>';
  const day=$('#datePicker').value;const stays=state.events.filter(e=>e.type==='stay'&&occursOn(e,day));const events=state.events.filter(e=>e.type!=='stay'&&occursOn(e,day)).sort((a,b)=>(a.start||'99').localeCompare(b.start||'99'));
  $('#stayTimeline').innerHTML=stays.length?stays.map(e=>`<article class="stayLane"><span class="stayLabel">宿泊</span><h3>${e.title}</h3><p>${e.mapPlace||mapPlaceName(e.mapUrl)||''}</p><p>チェックイン ${e.checkIn||'未定'}${e.checkInFrom?'（開始：'+e.checkInFrom+'〜）':''}　チェックアウト ${e.checkOut||'未定'}${e.checkOutUntil?'（締切：'+e.checkOutUntil+'）':''}</p>${e.ota?`<p>予約先：${e.ota}</p>`:''}${e.costLabel?`<p>費用：${e.costLabel}</p>`:''}${e.cancelPolicy?`<p>キャンセル：${e.cancelPolicy}</p>`:''}${safeMapUrl(e.mapUrl)?`<a class="mapLink" href="${safeMapUrl(e.mapUrl)}" target="_blank" rel="noopener noreferrer">Google Mapsで開く ↗</a>`:''}<button class="editButton" data-edit-event="${e.id}">編集</button></article>`).join(''):'';
  $('#timeline').innerHTML=events.length?events.map(e=>`<article class="event"><time>${e.start||'時間未定'}${e.end?'–'+e.end:''}</time><div class="eventBody" style="border-color:${typeColor(e.type||'activity')}"><strong>${e.title}</strong><small>${typeName(e.type||'activity')} · ${e.type==='transport'?(e.transportMode||'交通')+(e.reserved?' · 予約済み':' · 未予約')+(e.costLabel?' · '+e.costLabel:''):(e.mapPlace||mapPlaceName(e.mapUrl)||'')}</small>${safeMapUrl(e.mapUrl)?`<a class="mapLink" href="${safeMapUrl(e.mapUrl)}" target="_blank" rel="noopener noreferrer">Google Mapsで開く ↗</a>`:''}${e.participants.map(id=>`<span class="chip">${member(id)?.name}</span>`).join('')}<button class="editButton" data-edit-event="${e.id}">編集</button></div></article>`).join(''):'<p class="empty">この日の確定予定はまだありません。</p>';
  if(timelineView==='members')$('#timeline').innerHTML=state.members.map(m=>{const mine=events.filter(e=>e.participants.includes(m.id));return `<section class="memberLane"><h3><i class="dot" style="background:${m.color}"></i>${m.name}</h3>${mine.length?mine.map(e=>`<div class="laneEvent" style="border-color:${typeColor(e.type||'activity')}"><time>${e.start||'時間未定'}${e.end?'–'+e.end:''}</time><b>${e.title}</b><small>${typeName(e.type||'activity')} · ${e.mapPlace||mapPlaceName(e.mapUrl)||''}</small></div>`).join(''):'<p class="empty">予定はありません。</p>'}</section>`}).join('');
  $('#allPlans').innerHTML=`<h3>すべての予定</h3>${state.events.length?state.events.slice().sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).map(e=>`<div class="allPlan" style="border-left:4px solid ${typeColor(e.type||'activity')};padding-left:9px"><time>${e.date}${e.endDate&&e.endDate!==e.date?'〜'+e.endDate:''} ${e.start||''}</time><b>${e.title}</b> <small>${typeName(e.type||'activity')}</small></div>`).join(''):'<p class="empty">予定はまだありません。</p>'}`;
  document.querySelectorAll('[data-edit-event]').forEach(button=>{const del=document.createElement('button');del.className='editButton';del.textContent='削除';del.dataset.deleteEvent=button.dataset.editEvent;button.after(del)});
  $('#proposals').innerHTML=state.proposals.length?state.proposals.map(p=>{const mine=p.votes[state.current];return `<article class="proposal"><h3>${typeName(p.type||'other')}：${p.title}</h3><p class="meta">日付：${p.date}${p.endDate?'〜'+p.endDate:''}　${p.start?'時間：'+p.start+(p.end?'〜'+p.end:''):''}</p><p class="meta">場所：${p.mapPlace||mapPlaceName(p.mapUrl)||'未設定'}${p.type==='transport'?'　交通手段：'+(p.transportMode||'未設定')+'　'+(p.reserved?'予約済み':'未予約'):''}</p>${p.type==='stay'?`<p class="meta">チェックイン：${p.checkIn||'未定'}　開始：${p.checkInFrom||'未定'}　チェックアウト：${p.checkOut||'未定'}　締切：${p.checkOutUntil||'未定'}　予約先：${p.ota||'未設定'}　キャンセル：${p.cancelPolicy||'未設定'}</p>`:''}${p.cost?`<p class="meta">費用：${member(p.costPayer)?.name||'各自で支払い'} が ${yen(p.cost)}</p>`:''}<p class="meta">提案：${member(p.author)?.name||''}</p><div class="votes">${p.participants.map(id=>`<button class="vote ${p.votes[id]==='参加したい'?'active':''}" data-vote="${p.id}" data-person="${id}">${member(id)?.name}：${p.votes[id]||'未回答'}</button>`).join('')}</div><button class="adopt" data-adopt="${p.id}">この参加者で予定に追加</button><button class="editButton" data-edit-proposal="${p.id}">編集</button><button class="editButton" data-delete-proposal="${p.id}">削除</button></article>`}).join(''):'<p class="empty">未処理の提案はありません。気になることを気軽に追加しましょう。</p>';
  document.querySelectorAll('#proposals .proposal').forEach((card,index)=>{const p=state.proposals[index];if(!p?.costShares||!Object.keys(p.costShares).length)return;const values=Object.values(p.costShares),same=values.every(v=>v===values[0]),detail=document.createElement('p');detail.className='meta';detail.textContent=same?`1人あたり：${yen(values[0])}`:Object.entries(p.costShares).map(([id,n])=>`${member(id)?.name} ${yen(n)}`).join(' · ');card.querySelector('.votes')?.before(detail)});
  document.querySelectorAll('#proposals .proposal').forEach((card,index)=>{const url=safeMapUrl(state.proposals[index]?.mapUrl);if(!url)return;const link=document.createElement('a');link.className='mapLink';link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Google Mapsで開く ↗';card.querySelector('.votes')?.before(link)});
  document.querySelectorAll('#proposals .proposal').forEach((card,index)=>{const p=state.proposals[index];if(p?.votes?.[state.current]!=='未回答')return;const notice=document.createElement('p');notice.className='answerNeeded';notice.textContent='あなたは未回答です';card.querySelector('.votes')?.before(notice)});
  document.querySelectorAll('#proposals .proposal').forEach((card,index)=>{const p=state.proposals[index];if(!p||p.votes?.[state.current]==='参加したい')return;const join=document.createElement('button');join.className='primary';join.textContent='参加する';join.dataset.quickJoin=p.id;card.querySelector('.votes')?.after(join)});
  const net=netBalances(),paid=Object.fromEntries(state.members.map(m=>[m.id,0])),owed=Object.fromEntries(state.members.map(m=>[m.id,0]));(state.expenses||[]).forEach(e=>{paid[e.payer]=(paid[e.payer]||0)+e.amount;Object.entries(e.shares).forEach(([id,n])=>owed[id]=(owed[id]||0)+n)});$('#expenseSummary').innerHTML=state.members.map(m=>{const details=(state.expenses||[]).filter(e=>e.payer===m.id);return `<div class="balance">${m.name}<strong>${yen(paid[m.id])}</strong><span class="meta">負担額 ${yen(owed[m.id])}</span><details><summary>支出明細</summary>${details.length?details.map(e=>`<small>${e.title}　${yen(e.amount)}</small>`).join(''):'<small>支出はありません</small>'}</details></div>`}).join('');
  $('#expenses').innerHTML=(state.expenses||[]).length?state.expenses.slice().reverse().map(e=>`<article class="proposal"><div class="expenseLine"><h3>${e.title}</h3><b>${yen(e.amount)}</b></div><p class="meta">支払い：${member(e.payer)?.name}　${e.method==='equal'?'均等割り':e.method==='amount'?'金額指定':'割合指定'}</p><p class="meta">${Object.entries(e.shares).map(([id,n])=>`${member(id)?.name} ${yen(n)}`).join(' · ')}</p></article>`).join(''):'<p class="empty">費用はまだ登録されていません。</p>';
  const moves=settlement(net),done=state.settlementCompletions||{};$('#settlements').innerHTML=`<h3>精算</h3>${moves.length?moves.map(x=>{const id=`${x.from}:${x.to}:${x.n}`,completed=done[id];return `<div class="settlementRow ${completed?'isComplete':''}"><p><b>${member(x.from)?.name}</b> が <b>${member(x.to)?.name}</b> に ${yen(x.n)} 支払う</p><button class="settleButton" data-settlement-id="${id}">${completed?'完了を取り消す':'支払い完了'}</button></div>`}).join(''):'<p>精算は不要です。</p>'}`;
}
function choices(container,checked=true){container.innerHTML=state.members.map(m=>`<label class="choice"><input type="checkbox" name="participants" value="${m.id}" ${checked?'checked':''}>${m.name}</label>`).join('')}
$('#openMember').onclick=()=>byId('memberDialog').showModal();
$('#memberForm').addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target),name=d.get('name'),colors=['#e75d38','#2a9d8f','#4c78c2','#7a5bbb','#c46725','#687582'];state.members.push({id:crypto.randomUUID(),name,color:colors[state.members.length%colors.length]});log('参加者を追加',''+name);e.target.reset();byId('memberDialog').close();save()});
['openTripSetup','openTripSetupHeader','openTripSetupBottom'].forEach(id=>{const button=byId(id);if(button)button.onclick=()=>byId('tripSetupDialog').showModal()});
if($('#openJoinInfo'))$('#openJoinInfo').onclick=()=>alert('旅行の招待リンクを開くと、参加画面が表示されます。');
$('#tripSetupForm').addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.target),id=crypto.randomUUID(),name=d.get('personName');state.trip={title:d.get('title'),dates:'',onboarded:true,researchConsent:d.get('researchConsent')==='on'};state.members=[{id,name,color:'#e75d38'}];state.current=id;state.proposals=[];state.events=[];log('旅行を作成',state.trip.title);try{await createRemoteTrip()}catch(error){alert('共有旅行の作成に失敗しました：'+error.message)}byId('tripSetupDialog').close();save()});
$('#joinTripForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=new FormData(e.target);await joinRemoteTrip(d.get('inviteUrl'),d.get('participantId'),d.get('personName'));byId('joinInfoDialog').close()}catch(error){alert('参加できませんでした：'+error.message)}});
function proposalCostFields(){const box=document.querySelector('#proposalForm .inlineCost'),type=$('#proposalType').value,people=[...document.querySelectorAll('[name=…3446 tokens truncated…mData(e.target),mapUrl=d.get('mapUrl'),type=d.get('type'),people=d.getAll('schedulePeople'),old=editingEventId&&state.events.find(x=>x.id===editingEventId),eventId=old?.id||crypto.randomUUID(),shares={};if(mapUrl&&!safeMapUrl(mapUrl))return alert('httpsから始まるGoogle Mapsのリンクを入力してください。');let cost=0;if(type==='stay'){const unit=Number(d.get('stayCost'))||0;cost=d.get('stayChargeType')==='perPerson'?unit*people.length:unit;people.forEach((id,i)=>shares[id]=d.get('stayChargeType')==='perPerson'?unit:Math.floor(cost/people.length)+(i<cost%people.length?1:0))}else if(type==='transport'){document.querySelectorAll('.transportCost').forEach(x=>{const n=Number(x.value)||0;shares[x.dataset.id]=n;cost+=n})}else{cost=Number(d.get('genericCost'))||0;people.forEach((id,i)=>shares[id]=Math.floor(cost/people.length)+(i<cost%people.length?1:0))}if(cost&&!people.length)return alert('費用を分ける参加者を1人以上選んでください。');const entry={id:eventId,type,title:d.get('title'),date:d.get('date'),endDate:d.get('endDate'),start:d.get('start'),end:d.get('end'),checkIn:d.get('checkIn'),checkInFrom:d.get('checkInFrom'),checkOut:d.get('checkOut'),checkOutUntil:d.get('checkOutUntil'),transportMode:d.get('transportMode'),reserved:d.get('reserved')==='on',mapUrl,mapPlace:mapPlaceName(mapUrl),ota:d.get('ota'),cancelPolicy:d.get('cancelPolicy'),participants:people,author:old?.author||state.current,costLabel:cost?yen(cost):''};if(old)Object.assign(old,entry);else state.events.push(entry);state.expenses=(state.expenses||[]).filter(x=>x.scheduleId!==eventId);if(cost)addCostEntries(entry.title,d.get('costPayer'),shares,type==='stay'?d.get('stayChargeType'):'均等割り',eventId);log(old?'予定を編集':'予定を追加',entry.title);editingEventId=null;e.target.reset();byId('scheduleDialog').close();save()});
function splitFields(){const method=$('#splitMethod').value,people=[...document.querySelectorAll('[name=expensePeople]:checked')].map(x=>x.value);$('#splitInputs').innerHTML=method==='equal'?'':people.map(id=>`<label>${member(id)?.name}${method==='amount'?'の負担額（円）':'の割合（%）'}<input required class="splitValue" data-id="${id}" min="0" type="number" inputmode="decimal" value="${method==='ratio'?(100/Math.max(people.length,1)).toFixed(2):''}"></label>`).join('');$('#splitNotice').textContent=''}
$('#openExpense').onclick=()=>{let people=$('#expenseParticipants'),payer=$('#payerChoices');payer.innerHTML=state.members.map(m=>`<option value="${m.id}">${m.name}</option>`).join('');payer.value=state.current;people.innerHTML=state.members.map(m=>`<label class="choice"><input type="checkbox" name="expensePeople" value="${m.id}" checked>${m.name}</label>`).join('');splitFields();byId('expenseDialog').showModal()};$('#splitMethod').onchange=splitFields;$('#expenseParticipants').onchange=splitFields;
$('#expenseForm').addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target),amount=Number(d.get('amount')),method=d.get('method'),people=d.getAll('expensePeople'),shares={};if(!people.length)return $('#splitNotice').textContent='負担する人を選んでください。';if(method==='equal'){let base=Math.floor(amount/people.length),rest=amount-base*people.length;people.forEach((id,i)=>shares[id]=base+(i<rest?1:0))}else{let vals=[...document.querySelectorAll('.splitValue')];if(method==='amount'){vals.forEach(x=>shares[x.dataset.id]=Number(x.value));if(Object.values(shares).reduce((a,b)=>a+b,0)!==amount)return $('#splitNotice').textContent='負担額の合計を費用総額と一致させてください。'}else{let total=vals.reduce((a,x)=>a+Number(x.value),0);if(Math.abs(total-100)>.01)return $('#splitNotice').textContent='割合の合計を100%にしてください。';let used=0;vals.forEach((x,i)=>{shares[x.dataset.id]=i===vals.length-1?amount-used:Math.round(amount*Number(x.value)/100);used+=shares[x.dataset.id]})}}state.expenses=state.expenses||[];state.expenses.push({id:crypto.randomUUID(),title:d.get('title'),amount,payer:d.get('payer'),method,shares});log('費用を追加',d.get('title'));e.target.reset();byId('expenseDialog').close();save()});
$('#proposals').onclick=e=>{let vote=e.target.dataset.vote,adopt=e.target.dataset.adopt,edit=e.target.dataset.editProposal,del=e.target.dataset.deleteProposal,quick=e.target.dataset.quickJoin;if(quick){let p=state.proposals.find(x=>x.id===quick);p.votes[state.current]='参加したい';log('提案に参加',p.title);save();return}if(del){let i=state.proposals.findIndex(x=>x.id===del),p=state.proposals[i];if(confirm('この提案を削除しますか？')){state.proposals.splice(i,1);log('提案を削除',p.title);save()}return}if(edit){let p=state.proposals.find(x=>x.id===edit);editingProposalId=p.id;choices($('#participantChoices'),false);$('#proposalCostPayer').innerHTML=payerOptions();$('#proposalForm [name=type]').value=p.type||'other';$('#proposalForm [name=title]').value=p.title;$('#proposalForm [name=date]').value=p.date;$('#proposalForm [name=start]').value=p.start||'';$('#proposalForm [name=end]').value=p.end||'';$('#proposalForm [name=mapUrl]').value=p.mapUrl||'';$('#proposalForm [name=proposalCost]').value=p.cost||'';$('#proposalCostPayer').value=p.costPayer||state.current;document.querySelectorAll('[name=participants]').forEach(x=>x.checked=p.participants.includes(x.value));proposalFields();byId('proposalDialog').showModal();return}if(vote){let p=state.proposals.find(x=>x.id===vote);let id=e.target.dataset.person;if(id===state.current){p.votes[id]=p.votes[id]==='参加したい'?'行かない':'参加したい';log('提案への参加意思を変更',p.title);save()}}if(adopt){let i=state.proposals.findIndex(x=>x.id===adopt),p=state.proposals[i];let attendees=p.participants.filter(id=>p.votes[id]==='参加したい');let eventId=crypto.randomUUID();state.events.push({...p,id:eventId,participants:attendees.length?attendees:p.participants});if(p.cost){let people=attendees.length?attendees:p.participants,base=Math.floor(p.cost/people.length),rest=p.cost-base*people.length,shares={};people.forEach((id,n)=>shares[id]=base+(n<rest?1:0));addCostEntries(p.title,p.costPayer,shares,'均等割り',eventId)}state.proposals.splice(i,1);log('提案を予定に追加',p.title);save()}};
if($('#exportJson'))$('#exportJson').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='trip-together-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#exportIcs').onclick=()=>{const stamp=d=>d.replace(/[-:]/g,'').replace(/\.\d+/,'').replace('T','');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//TABIPU//JA'];state.events.filter(e=>e.date).forEach(e=>{const start=e.start?`${e.date}T${e.start}:00`:e.date.replaceAll('-','');const end=e.end?`${e.endDate||e.date}T${e.end}:00`:'';lines.push('BEGIN:VEVENT',`UID:${e.id}@tabipu`,`SUMMARY:${(e.title||'予定').replaceAll('\\n',' ')}`,e.start?`DTSTART:${stamp(start)}`:`DTSTART;VALUE=DATE:${start}`,end?`DTEND:${stamp(end)}`:'',e.mapPlace?`LOCATION:${e.mapPlace}`:'','END:VEVENT')});lines.push('END:VCALENDAR');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.filter(Boolean).join('\r\n')],{type:'text/calendar'}));a.download='tabipu.ics';a.click();URL.revokeObjectURL(a.href);log('iCalを書き出す','確定予定');save()};
$('#exportMyCostCsv').onclick=()=>{const current=member(state.current);if(!current)return alert('操作中のユーザーを選択してください。');const quote=value=>'"'+String(value??'').replaceAll('"','""')+'"';const rows=[['費用内容','支払った人','自分の負担額（円）','費用総額（円）','分け方']];(state.expenses||[]).filter(e=>Number(e.shares?.[state.current])>0).forEach(e=>rows.push([e.title,member(e.payer)?.name||'',e.shares[state.current],e.amount,e.method||'']));const csv='\uFEFF'+rows.map(row=>row.map(quote).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${current.name}-負担額明細.csv`;a.click();URL.revokeObjectURL(a.href);log('負担額明細CSVを出力',current.name);save()};
if($('#importJson'))$('#importJson').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{state=JSON.parse(r.result);state.logs=state.logs||[];save()}catch{alert('読み込めないファイルです。')}};r.readAsText(f)};
$('#importIcs').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const blocks=String(reader.result).split('BEGIN:VEVENT').slice(1),events=[];blocks.forEach(block=>{const get=name=>{const line=block.split(/\r?\n/).find(x=>x.startsWith(name));return line?.split(':').slice(1).join(':')||''},raw=get('DTSTART'),rawEnd=get('DTEND');if(!raw)return;const parse=v=>({date:`${v.slice(0,4)}-${v.slice(4,6)}-${v.slice(6,8)}`,time:v.includes('T')?`${v.slice(9,11)}:${v.slice(11,13)}`:''}),start=parse(raw),end=rawEnd?parse(rawEnd):{};events.push({id:crypto.randomUUID(),type:'other',title:get('SUMMARY')||'読み込み予定',date:start.date,endDate:end.date||'',start:start.time,end:end.time,mapPlace:get('LOCATION'),participants:state.members.map(m=>m.id),author:state.current})});state.events.push(...events);log('iCalを読み込む',`${events.length}件`);save();alert(`${events.length}件の予定を読み込みました。`)};reader.readAsText(file);e.target.value=''};
document.querySelectorAll('dialog .close').forEach(button=>button.onclick=e=>{e.preventDefault();button.closest('dialog').close()});
document.querySelectorAll('[name=endDate]').forEach(input=>input.parentElement.firstChild.textContent='終了日');
const switcher=document.createElement('span');switcher.className='viewSwitch';switcher.innerHTML='<button type="button" data-timeline-view="time" class="active">時間軸</button><button type="button" data-timeline-view="members">メンバー別</button>';$('#datePicker').after(switcher);switcher.onclick=e=>{const view=e.target.dataset.timelineView;if(!view)return;timelineView=view;switcher.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.timelineView===view));render()};
const allPlans=document.createElement('div');allPlans.id='allPlans';allPlans.className='allPlans';$('#timeline').after(allPlans);
document.addEventListener('click',e=>{const settlementId=e.target.dataset.settlementId;if(settlementId){const [from,to,amount]=settlementId.split(':');state.settlementCompletions=state.settlementCompletions||{};const detail=`${member(from)?.name||''} → ${member(to)?.name||''} ${yen(Number(amount))}`;if(state.settlementCompletions[settlementId]){if(!confirm(`${detail} の支払い完了を取り消しますか？`))return;delete state.settlementCompletions[settlementId];log('精算完了を取り消し',detail)}else{if(!confirm(`${detail} を支払い完了にしますか？`))return;state.settlementCompletions[settlementId]={by:state.current,at:new Date().toISOString()};log('精算を完了',detail)}save();return}const remove=e.target.dataset.deleteEvent;if(remove){const item=state.events.find(x=>x.id===remove);if(item&&confirm(`「${item.title}」を削除しますか？`)){state.events=state.events.filter(x=>x.id!==remove);state.expenses=(state.expenses||[]).filter(x=>x.scheduleId!==remove);log('予定を削除',item.title);save()}return}const id=e.target.dataset.editEvent;if(!id)return;const item=state.events.find(x=>x.id===id);if(item)openScheduleEditor(item)});
$('#datePicker').onchange=render; render();loadRemoteTrip();if(new URLSearchParams(location.search).get('start')==='1')setTimeout(()=>byId('tripSetupDialog').showModal(),0);
$('#copyInviteLink').onclick=async()=>{if(!state.trip.remoteId)return alert('共有旅行を作成してから招待リンクを発行できます。');try{const link=await createInviteLink();await navigator.clipboard.writeText(link);alert('招待リンクをコピーしました。')}catch(error){alert('招待リンクを作成できませんでした：'+error.message)}};
document.addEventListener('click',e=>{const id=e.target.dataset.editProposal;if(!id)return;const p=state.proposals.find(x=>x.id===id);if(!p)return;requestAnimationFrame(()=>{const form=$('#proposalForm');form.querySelector('[name=endDate]').value=p.endDate||'';form.querySelector('[name=checkIn]').value=p.checkIn||'';form.querySelector('[name=checkInFrom]').value=p.checkInFrom||'';form.querySelector('[name=checkOut]').value=p.checkOut||'';form.querySelector('[name=checkOutUntil]').value=p.checkOutUntil||'';form.querySelector('[name=transportMode]').value=p.transportMode||'飛行機';form.querySelector('[name=reserved]').checked=!!p.reserved;form.querySelector('[name=ota]').value=p.ota||'';form.querySelector('[name=cancelPolicy]').value=p.cancelPolicy||'';if($('#proposalGenericCostInput'))$('#proposalGenericCostInput').value=p.cost||''})});
document.addEventListener('click',e=>{const id=e.target.dataset.editEvent;if(!id)return;const item=state.events.find(x=>x.id===id);const expense=(state.expenses||[]).find(x=>x.scheduleId===id);if(!item||!expense)return;requestAnimationFrame(()=>{if($('#costPayerChoices'))$('#costPayerChoices').value=expense.payer;if($('#genericCostFields [name=genericCost]'))$('#genericCostFields [name=genericCost]').value=expense.amount;if($('#stayCostFields [name=stayCost]'))$('#stayCostFields [name=stayCost]').value=expense.amount;document.querySelectorAll('.transportCost').forEach(input=>input.value=expense.shares[input.dataset.id]||0)})});
function genericSplitHtml(prefix){return `<label>分け方<select id="${prefix}GenericMode"><option value="individual">参加者ごとに入力</option><option value="equal">全員同額</option><option value="total">合計を均等割り</option></select></label><div id="${prefix}GenericEntry"></div><input type="hidden" name="${prefix==='schedule'?'genericCost':'proposalCost'}" id="${prefix}GenericTotal">`}
function drawGenericSplit(prefix,people){const mode=$(`#${prefix}GenericMode`).value,entry=$(`#${prefix}GenericEntry`),total=$(`#${prefix}GenericTotal`),sync=()=>{const values=[...entry.querySelectorAll('.genericSplitCost')].map(x=>Number(x.value)||0);total.value=mode==='equal'?((values[0]||0)*people.length):values.reduce((a,b)=>a+b,0)};if(mode==='individual')entry.innerHTML=people.map(id=>`<label>${member(id)?.name}の費用（円）<input class="genericSplitCost" data-id="${id}" min="0" type="number" inputmode="numeric"></label>`).join('');else entry.innerHTML=`<label>${mode==='equal'?'一人あたりの費用（円）':'費用の合計（円）'}<input class="genericSplitCost" min="0" type="number" inputmode="numeric"></label>`;entry.querySelectorAll('.genericSplitCost').forEach(x=>x.oninput=sync);sync()}
function proposalCostFields(){const box=document.querySelector('#proposalForm .inlineCost'),type=$('#proposalType').value,people=[...document.querySelectorAll('[name=participants]:checked')].map(x=>x.value);if(!box.dataset.ready){box.dataset.ready='1';box.innerHTML='<h3>費用（任意）</h3><p><select name="proposalCostPayer" id="proposalCostPayer"></select> が、参加候補の分を払って、</p><div id="proposalGenericCost">'+genericSplitHtml('proposal')+'</div><div id="proposalStayCost"><label>料金の種類<select id="proposalStayChargeType"><option value="room">ルームチャージ</option><option value="perPerson">一人あたり</option></select></label><label id="proposalStayCostLabel">ルームチャージ（円）<input id="proposalStayCostInput" min="0" type="number"></label></div><div id="proposalTransportCost"><div id="proposalTransportCostInputs"></div></div></div>'}$('#proposalCostPayer').innerHTML=payerOptions();$('#proposalCostPayer').value=state.current;$('#proposalGenericCost').hidden=['stay','transport'].includes(type);$('#proposalStayCost').hidden=type!=='stay';$('#proposalTransportCost').hidden=type!=='transport';drawGenericSplit('proposal',people);$('#proposalTransportCostInputs').innerHTML=genericSplitHtml('proposalTransport').replace('proposalTransportGenericTotal','proposalTransportTotal');const transport=$('#proposalTransportCostInputs');transport.querySelector('select').onchange=()=>drawGenericSplit('proposalTransport',people);drawGenericSplit('proposalTransport',people)}
function scheduleCostFields(){const type=$('#scheduleType').value,people=[...document.querySelectorAll('[name=schedulePeople]:checked')].map(x=>x.value),box=$('#scheduleCostFields');if(!$('#genericCostFields')){const generic=document.createElement('div');generic.id='genericCostFields';box.append(generic)}box.hidden=false;$('#stayCostFields').hidden=type!=='stay';$('#transportCostFields').hidden=type!=='transport';$('#genericCostFields').hidden=['stay','transport'].includes(type);if(!['stay','transport'].includes(type)){$('#genericCostFields').innerHTML=genericSplitHtml('schedule');$('#scheduleGenericMode').onchange=()=>drawGenericSplit('schedule',people);drawGenericSplit('schedule',people)}}
$('#proposalForm').addEventListener('submit',()=>{const people=[...document.querySelectorAll('[name=participants]:checked')].map(x=>x.value),type=$('#proposalType').value;if(['stay','transport'].includes(type))return;const mode=$('#proposalGenericMode')?.value,values=[...document.querySelectorAll('#proposalGenericEntry .genericSplitCost')].map(x=>Number(x.value)||0),shares={};if(mode==='individual')people.forEach((id,i)=>shares[id]=values[i]||0);else if(mode==='equal')people.forEach(id=>shares[id]=values[0]||0);else{const total=values[0]||0,base=Math.floor(total/people.length),rest=total-base*people.length;people.forEach((id,i)=>shares[id]=base+(i<rest?1:0))}let hidden=$('#proposalForm [name=proposalShares]');if(!hidden){hidden=document.createElement('input');hidden.type='hidden';hidden.name='proposalShares';$('#proposalForm').append(hidden)}hidden.value=JSON.stringify(shares)},true);
function proposalCostFields(){const box=$('#proposalForm .inlineCost'),type=$('#proposalType').value,people=[...document.querySelectorAll('[name=participants]:checked')].map(x=>x.value);if(!box.dataset.ready){box.dataset.ready='1';box.innerHTML='<h3>費用（任意）</h3><p><select name="proposalCostPayer" id="proposalCostPayer"></select> が、参加候補の分を払って、</p><div id="proposalGenericCost">'+genericSplitHtml('proposal')+'</div><div id="proposalStayCost"><label>料金（円）<input id="proposalStayCostInput" type="number"></label></div><div id="proposalTransportCost">'+genericSplitHtml('proposalTransport')+'</div></div>'}$('#proposalCostPayer').innerHTML=payerOptions();$('#proposalGenericCost').hidden=['stay','transport'].includes(type);$('#proposalStayCost').hidden=type!=='stay';$('#proposalTransportCost').hidden=type!=='transport';if(!['stay','transport'].includes(type)){drawGenericSplit('proposal',people)}else if(type==='transport'){drawGenericSplit('proposalTransport',people);$('#proposalTransportGenericEntry').querySelectorAll('.genericSplitCost').forEach(x=>x.classList.add('proposalTransportCost'))}else{$('#proposalStayCostInput').oninput=()=>$('#proposalForm [name=proposalCost]').value=$('#proposalStayCostInput').value||''}}
function scheduleCostFields(){const type=$('#scheduleType').value,people=[...document.querySelectorAll('[name=schedulePeople]:checked')].map(x=>x.value),box=$('#scheduleCostFields');if(!$('#genericCostFields')){const generic=document.createElement('div');generic.id='genericCostFields';box.append(generic)}box.hidden=false;$('#stayCostFields').hidden=type!=='stay';$('#transportCostFields').hidden=type!=='transport';$('#genericCostFields').hidden=['stay','transport'].includes(type);if(!['stay','transport'].includes(type)){$('#genericCostFields').innerHTML=genericSplitHtml('schedule');$('#scheduleGenericMode').onchange=()=>drawGenericSplit('schedule',people);drawGenericSplit('schedule',people)}}

