const key='trip-together-v1';
const defaultState={trip:{title:'石垣島旅行',dates:'8/17〜8/19'},members:[{id:'a',name:'しゅうた',color:'#e75d38'},{id:'b',name:'Aさん',color:'#2a9d8f'},{id:'c',name:'Bさん',color:'#4c78c2'}],current:'a',proposals:[],events:[],expenses:[]};
let state=JSON.parse(localStorage.getItem(key)||'null')||defaultState;
const $=s=>document.querySelector(s); const byId=id=>document.getElementById(id);
function save(){localStorage.setItem(key,JSON.stringify(state));render()}
function member(id){return state.members.find(x=>x.id===id)}
function safeMapUrl(value){try{const url=new URL(value);return url.protocol==='https:'?url.href:''}catch{return ''}}
function mapPlaceName(value){try{const url=new URL(value),path=decodeURIComponent(url.pathname);let found=path.match(/\/place\/([^/]+)/);if(found)return found[1].replace(/\+/g,' ');let query=url.searchParams.get('query')||url.searchParams.get('q');return query?query.replace(/\+/g,' '):''}catch{return ''}}
function yen(n){return new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n)}
function netBalances(){const net=Object.fromEntries(state.members.map(m=>[m.id,0]));(state.expenses||[]).forEach(e=>{net[e.payer]+=e.amount;Object.entries(e.shares).forEach(([id,n])=>net[id]-=n)});return net}
function settlement(net){let debt=Object.entries(net).filter(([,n])=>n<-.5).map(([id,n])=>({id,n:-n})),credit=Object.entries(net).filter(([,n])=>n>.5).map(([id,n])=>({id,n})),out=[];while(debt.length&&credit.length){let a=debt[0],b=credit[0],n=Math.min(a.n,b.n);out.push({from:a.id,to:b.id,n:Math.round(n)});a.n-=n;b.n-=n;if(a.n<.5)debt.shift();if(b.n<.5)credit.shift()}return out}
function render(){
  $('#tripTitle').textContent=state.trip.title; $('#tripDates').textContent=state.trip.dates;
  const cur=member(state.current);$('#identityButton').textContent='👤 操作中：'+(cur?.name||'未選択');$('#proposalCount').textContent=state.proposals.length;
  $('#members').innerHTML=state.members.map(m=>`<span class="member"><i class="dot" style="background:${m.color}"></i>${m.name}</span>`).join('')||'<p class="empty">参加者を追加してください。</p>';
  const day=$('#datePicker').value;const events=state.events.filter(e=>!day||e.date===day).sort((a,b)=>(a.start||'99').localeCompare(b.start||'99'));
  $('#timeline').innerHTML=events.length?events.map(e=>`<article class="event"><time>${e.start||'時間未定'}${e.end?'–'+e.end:''}</time><div class="eventBody" style="border-color:${member(e.participants[0])?.color||'#e75d38'}"><strong>${e.title}</strong><small>${e.mapPlace||mapPlaceName(e.mapUrl)||''}</small>${safeMapUrl(e.mapUrl)?`<a class="mapLink" href="${safeMapUrl(e.mapUrl)}" target="_blank" rel="noopener noreferrer">Google Mapsで開く ↗</a>`:''}${e.participants.map(id=>`<span class="chip">${member(id)?.name}</span>`).join('')}</div></article>`).join(''):'<p class="empty">この日の確定予定はまだありません。</p>';
  $('#proposals').innerHTML=state.proposals.length?state.proposals.map(p=>{const mine=p.votes[state.current];return `<article class="proposal"><h3>${p.title}</h3><p class="meta">${p.date}${p.start?' '+p.start:''}${p.place?' · '+p.place:''}　提案：${member(p.author)?.name||''}</p><div class="votes">${p.participants.map(id=>`<button class="vote ${p.votes[id]==='参加したい'?'active':''}" data-vote="${p.id}" data-person="${id}">${member(id)?.name}：${p.votes[id]||'未回答'}</button>`).join('')}</div><button class="adopt" data-adopt="${p.id}">この参加者で予定に追加</button></article>`}).join(''):'<p class="empty">未処理の提案はありません。気になることを気軽に追加しましょう。</p>';
  const net=netBalances();$('#expenseSummary').innerHTML=state.members.map(m=>`<div class="balance">${m.name}<strong class="${net[m.id]>=0?'positive':'negative'}">${net[m.id]>=0?'+':''}${yen(net[m.id])}</strong></div>`).join('');
  $('#expenses').innerHTML=(state.expenses||[]).length?state.expenses.slice().reverse().map(e=>`<article class="proposal"><div class="expenseLine"><h3>${e.title}</h3><b>${yen(e.amount)}</b></div><p class="meta">支払い：${member(e.payer)?.name}　${e.method==='equal'?'均等割り':e.method==='amount'?'金額指定':'割合指定'}</p><p class="meta">${Object.entries(e.shares).map(([id,n])=>`${member(id)?.name} ${yen(n)}`).join(' · ')}</p></article>`).join(''):'<p class="empty">費用はまだ登録されていません。</p>';
  const moves=settlement(net);$('#settlements').innerHTML=`<h3>精算の提案</h3>${moves.length?moves.map(x=>`<p><b>${member(x.from)?.name}</b> → <b>${member(x.to)?.name}</b>　${yen(x.n)}</p>`).join(''):'<p>精算は完了しています。</p>'}`;
}
function choices(container,checked=true){container.innerHTML=state.members.map(m=>`<label class="choice"><input type="checkbox" name="participants" value="${m.id}" ${checked?'checked':''}>${m.name}</label>`).join('')}
$('#openMember').onclick=()=>byId('memberDialog').showModal();
$('#memberForm').addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target);state.members.push({id:crypto.randomUUID(),name:d.get('name'),color:d.get('color')});e.target.reset();byId('memberDialog').close();save()});
function openProposal(){choices($('#participantChoices'));$('#proposalForm [name=date]').value=$('#datePicker').value||new Date().toISOString().slice(0,10);byId('proposalDialog').showModal()}
$('#openProposal').onclick=openProposal;$('#openProposalSmall').onclick=openProposal;
$('#proposalForm').addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target),participants=d.getAll('participants'),mapUrl=d.get('mapUrl');if(mapUrl&&!safeMapUrl(mapUrl))return alert('httpsから始まるGoogle Mapsのリンクを入力してください。');let p={id:crypto.randomUUID(),title:d.get('title'),date:d.get('date'),start:d.get('start'),end:d.get('end'),mapUrl,mapPlace:mapPlaceName(mapUrl),participants,author:state.current,votes:{}};participants.forEach(id=>p.votes[id]=id===state.current?'参加したい':'未回答');state.proposals.unshift(p);e.target.reset();byId('proposalDialog').close();save()});
$('#identityButton').onclick=()=>{let box=$('#identityChoices');box.innerHTML='';state.members.forEach(m=>{let b=document.createElement('button');b.className='identityChoice';b.value='cancel';b.textContent=m.name;b.onclick=()=>{state.current=m.id;byId('identityDialog').close();save()};box.append(b)});byId('identityDialog').showModal()};
function splitFields(){const method=$('#splitMethod').value,people=[...document.querySelectorAll('[name=expensePeople]:checked')].map(x=>x.value);$('#splitInputs').innerHTML=method==='equal'?'':people.map(id=>`<label>${member(id)?.name}${method==='amount'?'の負担額（円）':'の割合（%）'}<input required class="splitValue" data-id="${id}" min="0" type="number" inputmode="decimal" value="${method==='ratio'?(100/Math.max(people.length,1)).toFixed(2):''}"></label>`).join('');$('#splitNotice').textContent=''}
$('#openExpense').onclick=()=>{let people=$('#expenseParticipants'),payer=$('#payerChoices');payer.innerHTML=state.members.map(m=>`<option value="${m.id}">${m.name}</option>`).join('');payer.value=state.current;people.innerHTML=state.members.map(m=>`<label class="choice"><input type="checkbox" name="expensePeople" value="${m.id}" checked>${m.name}</label>`).join('');splitFields();byId('expenseDialog').showModal()};$('#splitMethod').onchange=splitFields;$('#expenseParticipants').onchange=splitFields;
$('#expenseForm').addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target),amount=Number(d.get('amount')),method=d.get('method'),people=d.getAll('expensePeople'),shares={};if(!people.length)return $('#splitNotice').textContent='負担する人を選んでください。';if(method==='equal'){let base=Math.floor(amount/people.length),rest=amount-base*people.length;people.forEach((id,i)=>shares[id]=base+(i<rest?1:0))}else{let vals=[...document.querySelectorAll('.splitValue')];if(method==='amount'){vals.forEach(x=>shares[x.dataset.id]=Number(x.value));if(Object.values(shares).reduce((a,b)=>a+b,0)!==amount)return $('#splitNotice').textContent='負担額の合計を費用総額と一致させてください。'}else{let total=vals.reduce((a,x)=>a+Number(x.value),0);if(Math.abs(total-100)>.01)return $('#splitNotice').textContent='割合の合計を100%にしてください。';let used=0;vals.forEach((x,i)=>{shares[x.dataset.id]=i===vals.length-1?amount-used:Math.round(amount*Number(x.value)/100);used+=shares[x.dataset.id]})}}state.expenses=state.expenses||[];state.expenses.push({id:crypto.randomUUID(),title:d.get('title'),amount,payer:d.get('payer'),method,shares});e.target.reset();byId('expenseDialog').close();save()});
$('#proposals').onclick=e=>{let vote=e.target.dataset.vote,adopt=e.target.dataset.adopt;if(vote){let p=state.proposals.find(x=>x.id===vote);let id=e.target.dataset.person;if(id===state.current)p.votes[id]=p.votes[id]==='参加したい'?'行かない':'参加したい';save()}if(adopt){let i=state.proposals.findIndex(x=>x.id===adopt),p=state.proposals[i];let attendees=p.participants.filter(id=>p.votes[id]==='参加したい');state.events.push({...p,participants:attendees.length?attendees:p.participants});state.proposals.splice(i,1);save()}};
$('#exportJson').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='trip-together-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#importJson').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{state=JSON.parse(r.result);save()}catch{alert('読み込めないファイルです。')}};r.readAsText(f)};
$('#datePicker').onchange=render; render();

